packages:
  - packages/*
  - sites/*
  - examples/*

catalog:
  '@fastify/express': ^4.0.2
  '@graphql-codegen/cli': ^6.0.0
  '@graphql-codegen/typed-document-node': ^6.0.0
  '@graphql-codegen/typescript': ^5.0.0
  '@graphql-codegen/typescript-operations': ^5.0.0
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.4
  '@types/express': 5.0.3
  '@types/koa': ^3.0.0
  '@types/node': 24.3.0
  '@types/ws': ^8.18.1
  chokidar-cli: ^3.0.0
  concurrently: ^9.2.1
  esbuild: 0.25.10
  express: 5.1.0
  fastify: ^5.5.0
  get-port: ^7.1.0
  koa: ^3.0.1
  rimraf: ^6.0.1
  typescript: 5.9.2
  uuid: ^11.1.0
  vitest: ^3.2.4
  ws: ^8.18.3
