packages:
  - packages/*
  - sites/*
  - examples/*

catalog:
  "@swc/cli": "^0.7.8"
  "@swc/core": "^1.13.4"
  "@types/express": ^5.0.3
  "@fastify/express": ^4.0.2
  "@types/koa": ^3.0.0
  "@types/node": 24.3.0
  "@types/ws": ^8.18.1
  chokidar-cli: "^3.0.0"
  concurrently: ^9.2.0
  express: ^5.1.0
  fastify: ^5.5.0
  koa: ^3.0.1
  get-port: ^7.1.0
  rimraf: ^6.0.1
  typescript: ^5.9.2
  uuid: ^11.1.0
  vitest: ^3.2.4
  ws: ^8.18.3
